linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 30
  cyclop:
    max-complexity: 30
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  enable-all: true
  disable:
    - wrapcheck
    - nlreturn
    - gomnd
    - goerr113
    - exhaustivestruct
    - wsl
    - whitespace
    - lll
    - scopelint
    - nestif
    - funlen
    - paralleltest
    - godot
    - varnamelen
    - ireturn

    - goconst
    - exhaustruct
    - dupword
    - interfacebloat
    - gci

    - ifshort # deprecated
    - structcheck # deprecated
    - deadcode # deprecated
    - nosnakecase # deprecated
    - varcheck # deprecated
    - rowserrcheck # deprecated
    - sqlclosecheck # deprecated
    - wastedassign # deprecated
    - golint # deprecated
    - interfacer # deprecated
    - maligned # deprecated

run:
  skip-dirs:
    - test
