// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestBalanceNormal0(t *testing.T) {
	err := ProcessLine("balance roundrobin", &parsers.Balance{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestBalanceFail0(t *testing.T) {
	err := ProcessLine("balance something", &parsers.Balance{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestBalanceFail1(t *testing.T) {
	err := ProcessLine("balance", &parsers.Balance{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestBalanceFail2(t *testing.T) {
	err := ProcessLine("---", &parsers.Balance{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestBalanceFail3(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.Balance{})
	if err == nil {
		t.Errorf("no data")
	}
}
