// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestCpuMapNormal0(t *testing.T) {
	err := ProcessLine("cpu-map 1-4 0-3", &parsers.CpuMap{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestCpuMapNormal1(t *testing.T) {
	err := ProcessLine("cpu-map 1/all 0-3", &parsers.CpuMap{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestCpuMapNormal2(t *testing.T) {
	err := ProcessLine("cpu-map auto:1-4 0-3", &parsers.CpuMap{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestCpuMapNormal3(t *testing.T) {
	err := ProcessLine("cpu-map auto:1-4 0-1 2-3", &parsers.CpuMap{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestCpuMapFail0(t *testing.T) {
	err := ProcessLine("cpu-map", &parsers.CpuMap{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestCpuMapFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.CpuMap{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestCpuMapFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.CpuMap{})
	if err == nil {
		t.Errorf("no data")
	}
}
