// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestDaemonNormal0(t *testing.T) {
	err := ProcessLine("daemon", &parsers.Daemon{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestDaemonNormal1(t *testing.T) {
	err := ProcessLine("daemon # comment", &parsers.Daemon{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestDaemonFail0(t *testing.T) {
	err := ProcessLine("---", &parsers.Daemon{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestDaemonFail1(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.Daemon{})
	if err == nil {
		t.Errorf("no data")
	}
}
