// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestDefaultServerNormal0(t *testing.T) {
	err := ProcessLine("default-server inter 1000 weight 13", &parsers.DefaultServer{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestDefaultServerFail0(t *testing.T) {
	err := ProcessLine("default-server", &parsers.DefaultServer{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestDefaultServerFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.DefaultServer{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestDefaultServerFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.DefaultServer{})
	if err == nil {
		t.Errorf("no data")
	}
}
