// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestErrorFileNormal0(t *testing.T) {
	err := ProcessLine("errorfile 400 /etc/haproxy/errorfiles/400badreq.http", &parsers.ErrorFile{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestErrorFileNormal1(t *testing.T) {
	err := ProcessLine("errorfile 408 /dev/null  # work around Chrome pre-connect bug", &parsers.ErrorFile{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestErrorFileNormal2(t *testing.T) {
	err := ProcessLine("errorfile 403 /etc/haproxy/errorfiles/403forbid.http", &parsers.ErrorFile{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestErrorFileNormal3(t *testing.T) {
	err := ProcessLine("errorfile 503 /etc/haproxy/errorfiles/503sorry.http", &parsers.ErrorFile{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestErrorFileFail0(t *testing.T) {
	err := ProcessLine("errorfile", &parsers.ErrorFile{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestErrorFileFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.ErrorFile{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestErrorFileFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.ErrorFile{})
	if err == nil {
		t.Errorf("no data")
	}
}
