// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestGroupNormal0(t *testing.T) {
	err := ProcessLine("group G1 users tiger,scott", &parsers.Group{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestGroupNormal1(t *testing.T) {
	err := ProcessLine("group G1", &parsers.Group{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestGroupFail0(t *testing.T) {
	err := ProcessLine("group", &parsers.Group{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestGroupFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.Group{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestGroupFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.Group{})
	if err == nil {
		t.Errorf("no data")
	}
}
