// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestMasterWorkerNormal0(t *testing.T) {
	err := ProcessLine("master-worker", &parsers.MasterWorker{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestMasterWorkerNormal1(t *testing.T) {
	err := ProcessLine("master-worker # comment", &parsers.MasterWorker{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestMasterWorkerFail0(t *testing.T) {
	err := ProcessLine("---", &parsers.MasterWorker{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestMasterWorkerFail1(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.MasterWorker{})
	if err == nil {
		t.Errorf("no data")
	}
}
