// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestMaxConnNormal0(t *testing.T) {
	err := ProcessLine("maxconn 10000", &parsers.MaxConn{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestMaxConnNormal1(t *testing.T) {
	err := ProcessLine("maxconn 10000 # comment", &parsers.MaxConn{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestMaxConnFail0(t *testing.T) {
	err := ProcessLine("maxconn", &parsers.MaxConn{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestMaxConnFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.MaxConn{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestMaxConnFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.MaxConn{})
	if err == nil {
		t.Errorf("no data")
	}
}
