// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestModeNormal0(t *testing.T) {
	err := ProcessLine("mode tcp", &parsers.Mode{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestModeNormal1(t *testing.T) {
	err := ProcessLine("mode http", &parsers.Mode{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestModeNormal2(t *testing.T) {
	err := ProcessLine("mode health", &parsers.Mode{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestModeNormal3(t *testing.T) {
	err := ProcessLine("mode tcp # comment", &parsers.Mode{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestModeFail0(t *testing.T) {
	err := ProcessLine("mode", &parsers.Mode{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestModeFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.Mode{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestModeFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.Mode{})
	if err == nil {
		t.Errorf("no data")
	}
}
