// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestNameserverNormal0(t *testing.T) {
	err := ProcessLine("nameserver dns1 10.0.0.1:53", &parsers.Nameserver{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestNameserverNormal1(t *testing.T) {
	err := ProcessLine("nameserver dns1 10.0.0.1:53 # comment", &parsers.Nameserver{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestNameserverFail0(t *testing.T) {
	err := ProcessLine("nameserver", &parsers.Nameserver{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestNameserverFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.Nameserver{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestNameserverFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.Nameserver{})
	if err == nil {
		t.Errorf("no data")
	}
}
