// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestNbProcNormal0(t *testing.T) {
	err := ProcessLine("nbproc 4", &parsers.NbProc{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestNbProcNormal1(t *testing.T) {
	err := ProcessLine("nbproc 4 # comment", &parsers.NbProc{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestNbProcFail0(t *testing.T) {
	err := ProcessLine("nbproc", &parsers.NbProc{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestNbProcFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.NbProc{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestNbProcFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.NbProc{})
	if err == nil {
		t.Errorf("no data")
	}
}
