// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestOptionHttpchkNormal0(t *testing.T) {
	err := ProcessLine("option httpchk OPTIONS * HTTP/1.1\\r\\nHost:\\ www", &parsers.OptionHttpchk{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestOptionHttpchkFail0(t *testing.T) {
	err := ProcessLine("---", &parsers.OptionHttpchk{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestOptionHttpchkFail1(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.OptionHttpchk{})
	if err == nil {
		t.Errorf("no data")
	}
}
