// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestOptionHTTPLogNormal0(t *testing.T) {
	err := ProcessLine("option httplog", &parsers.OptionHTTPLog{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestOptionHTTPLogNormal1(t *testing.T) {
	err := ProcessLine("no option httplog", &parsers.OptionHTTPLog{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestOptionHTTPLogNormal2(t *testing.T) {
	err := ProcessLine("option httplog clf", &parsers.OptionHTTPLog{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestOptionHTTPLogNormal3(t *testing.T) {
	err := ProcessLine("option httplog # comment", &parsers.OptionHTTPLog{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestOptionHTTPLogNormal4(t *testing.T) {
	err := ProcessLine("option httplog clf # comment", &parsers.OptionHTTPLog{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestOptionHTTPLogFail0(t *testing.T) {
	err := ProcessLine("---", &parsers.OptionHTTPLog{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestOptionHTTPLogFail1(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.OptionHTTPLog{})
	if err == nil {
		t.Errorf("no data")
	}
}
