// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestPeerNormal0(t *testing.T) {
	err := ProcessLine("peer name 127.0.0.1:8080", &parsers.Peer{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestPeerFail0(t *testing.T) {
	err := ProcessLine("peer name 127.0.0.1", &parsers.Peer{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestPeerFail1(t *testing.T) {
	err := ProcessLine("peer name :8080", &parsers.Peer{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestPeerFail2(t *testing.T) {
	err := ProcessLine("peer", &parsers.Peer{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestPeerFail3(t *testing.T) {
	err := ProcessLine("---", &parsers.Peer{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestPeerFail4(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.Peer{})
	if err == nil {
		t.Errorf("no data")
	}
}
