// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestStatsTimeoutNormal0(t *testing.T) {
	err := ProcessLine("stats timeout 4", &parsers.StatsTimeout{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestStatsTimeoutNormal1(t *testing.T) {
	err := ProcessLine("stats timeout 4 # comment", &parsers.StatsTimeout{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestStatsTimeoutFail0(t *testing.T) {
	err := ProcessLine("stats timeout", &parsers.StatsTimeout{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestStatsTimeoutFail1(t *testing.T) {
	err := ProcessLine("stats", &parsers.StatsTimeout{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestStatsTimeoutFail2(t *testing.T) {
	err := ProcessLine("timeout", &parsers.StatsTimeout{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestStatsTimeoutFail3(t *testing.T) {
	err := ProcessLine("---", &parsers.StatsTimeout{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestStatsTimeoutFail4(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.StatsTimeout{})
	if err == nil {
		t.Errorf("no data")
	}
}
