// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestSocketNormal0(t *testing.T) {
	err := ProcessLine("stats socket 127.0.0.1:8080", &parsers.Socket{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestSocketNormal1(t *testing.T) {
	err := ProcessLine("stats socket 127.0.0.1:8080 mode admin", &parsers.Socket{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestSocketNormal2(t *testing.T) {
	err := ProcessLine("stats socket /some/path/to/socket", &parsers.Socket{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestSocketNormal3(t *testing.T) {
	err := ProcessLine("stats socket /some/path/to/socket mode admin", &parsers.Socket{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestSocketNormal4(t *testing.T) {
	err := ProcessLine("stats socket 127.0.0.1 backup", &parsers.Socket{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestSocketFail0(t *testing.T) {
	err := ProcessLine("stats socket", &parsers.Socket{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestSocketFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.Socket{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestSocketFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.Socket{})
	if err == nil {
		t.Errorf("no data")
	}
}
