// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestStickNormal0(t *testing.T) {
	err := ProcessLine("stick on src table pop if !localhost", &parsers.Stick{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestStickNormal1(t *testing.T) {
	err := ProcessLine("stick match src table pop if !localhost", &parsers.Stick{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestStickNormal2(t *testing.T) {
	err := ProcessLine("stick store-request src table pop if !localhost", &parsers.Stick{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestStickFail0(t *testing.T) {
	err := ProcessLine("stick", &parsers.Stick{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestStickFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.Stick{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestStickFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.Stick{})
	if err == nil {
		t.Errorf("no data")
	}
}
