// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestUseBackendNormal0(t *testing.T) {
	err := ProcessLine("use_backend test if TRUE", &parsers.UseBackend{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestUseBackendNormal1(t *testing.T) {
	err := ProcessLine("use_backend test if TRUE #deny", &parsers.UseBackend{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestUseBackendFail0(t *testing.T) {
	err := ProcessLine("use_backend", &parsers.UseBackend{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestUseBackendFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.UseBackend{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestUseBackendFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.UseBackend{})
	if err == nil {
		t.Errorf("no data")
	}
}
