// Code generated by go generate; DO NOT EDIT.
package tests

import (
	"testing"

	"github.com/haproxytech/config-parser/parsers"
)


func TestUserNormal0(t *testing.T) {
	err := ProcessLine("user tiger password $6$k6y3o.eP$JlKBx(...)xHSwRv6J.C0/D7cV91 groups G1", &parsers.User{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestUserNormal1(t *testing.T) {
	err := ProcessLine("user panda insecure-password elgato groups G1,G2", &parsers.User{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestUserNormal2(t *testing.T) {
	err := ProcessLine("user bear insecure-password hello groups G2", &parsers.User{})
	if err != nil {
		t.Errorf(err.Error())
	}
}
func TestUserFail0(t *testing.T) {
	err := ProcessLine("user", &parsers.User{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestUserFail1(t *testing.T) {
	err := ProcessLine("---", &parsers.User{})
	if err == nil {
		t.Errorf("no data")
	}
}
func TestUserFail2(t *testing.T) {
	err := ProcessLine("--- ---", &parsers.User{})
	if err == nil {
		t.Errorf("no data")
	}
}
