// Code generated by go generate; DO NOT EDIT.
package parsers

import (
	"github.com/haproxytech/config-parser/common"
	"github.com/haproxytech/config-parser/errors"
	"github.com/haproxytech/config-parser/types"
)

func (p *OptionSmtpchk) Init() {
    p.data = nil
}

func (p *OptionSmtpchk) GetParserName() string {
	return "option smtpchk"
}

func (p *OptionSmtpchk) Get(createIfNotExist bool) (common.ParserData, error) {
	if p.data == nil {
		if createIfNotExist {
			p.data = &types.OptionSmtpchk{}
			return p.data, nil
		}
		return nil, errors.FetchError
	}
	return p.data, nil
}

func (p *OptionSmtpchk) GetOne(index int) (common.ParserData, error) {
	if index > 0 {
		return nil, errors.FetchError
	}
	if p.data == nil {
		return nil, errors.FetchError
	}
	return p.data, nil
}

func (p *OptionSmtpchk) Delete(index int) error {
	p.Init()
	return nil
}

func (p *OptionSmtpchk) Insert(data common.ParserData, index int) error {
	return p.Set(data, index)
}

func (p *OptionSmtpchk) Set(data common.ParserData, index int) error {
	if data == nil {
		p.Init()
		return nil
	}
	switch newValue := data.(type) {
	case *types.OptionSmtpchk:
		p.data = newValue
	case types.OptionSmtpchk:
		p.data = &newValue
	default:
		return errors.InvalidData
	}
	return nil
}
