// Code generated by go generate; DO NOT EDIT.
package simple

import (
	"github.com/haproxytech/config-parser/common"
	"github.com/haproxytech/config-parser/errors"
	"github.com/haproxytech/config-parser/types"
)

func (p *SimpleNumber) Init() {
    p.data = nil
}

func (p *SimpleNumber) GetParserName() string {
    return p.Name
}

func (p *SimpleNumber) Get(createIfNotExist bool) (common.ParserData, error) {
	if p.data == nil {
		if createIfNotExist {
			p.data = &types.Int64C{}
			return p.data, nil
		}
		return nil, errors.FetchError
	}
	return p.data, nil
}

func (p *SimpleNumber) GetOne(index int) (common.ParserData, error) {
	if index > 0 {
		return nil, errors.FetchError
	}
	if p.data == nil {
		return nil, errors.FetchError
	}
	return p.data, nil
}

func (p *SimpleNumber) Delete(index int) error {
	p.Init()
	return nil
}

func (p *SimpleNumber) Insert(data common.ParserData, index int) error {
	return p.Set(data, index)
}

func (p *SimpleNumber) Set(data common.ParserData, index int) error {
	if data == nil {
		p.Init()
		return nil
	}
	switch newValue := data.(type) {
	case *types.Int64C:
		p.data = newValue
	case types.Int64C:
		p.data = &newValue
	default:
		return errors.InvalidData
	}
	return nil
}
