// Code generated by go generate; DO NOT EDIT.
package extra

import (
	"github.com/haproxytech/config-parser/common"
	"github.com/haproxytech/config-parser/errors"
	"github.com/haproxytech/config-parser/types"
)

func (p *ConfigVersion) GetParserName() string {
    return p.Name
}

func (p *ConfigVersion) GetOne(index int) (common.ParserData, error) {
	if index > 0 {
		return nil, errors.FetchError
	}
	if p.data == nil {
		return nil, errors.FetchError
	}
	return p.data, nil
}

func (p *ConfigVersion) Delete(index int) error {
	p.Init()
	return nil
}

func (p *ConfigVersion) Insert(data common.ParserData, index int) error {
	return p.Set(data, index)
}

func (p *ConfigVersion) Set(data common.ParserData, index int) error {
	if data == nil {
		p.Init()
		return nil
	}
	switch newValue := data.(type) {
	case *types.ConfigVersion:
		p.data = newValue
	case types.ConfigVersion:
		p.data = &newValue
	default:
		return errors.InvalidData
	}
	return nil
}
